/** The 25 target languages offered by the highlight toolbar's Translate action. */
export const LANGUAGES: string[] = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Polish',
  'Ukrainian',
  'Turkish',
  'Arabic',
  'Hebrew',
  'Hindi',
  'Bengali',
  'Urdu',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Swedish',
  'Greek',
];
